name: Demo

on:
    push:
        branches: [ main ]
    pull_request: null
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 5 * *"

env:
    ANSICON: 1

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Test ${{ matrix.php }}; Symfony ${{ matrix.symfony-version }} (${{ matrix.dependency }})
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '8.2'
                dependency: [ highest ]
                symfony-version:
                    - 'unchanged'
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: composer, flex
                    coverage: none

            -   run: composer install
            -   run: vendor/bin/phpunit